### ISSUE TITLE
unable to run the model in iOS app 

### ISSUE THREAD

**Issue by quixoticblink** [vincentfpgarcia/from-pytorch-to-coreml#2]
Thank you for the tutorial. 
The model runs well on my desktop. 
However, when I port to iOS, the model does not initialize. 
Since it is taking input of array whereas it should take an image as input.
Were you able to resolve that ?

inputs: (
"my_input : MultiArray (Float32, 3 x 32 x 32)"
)

**Comment by vincentfpgarcia** [comment]
Hi. Happy to read that the model runs well on desktop!

This tutorial purpose is to explain how to convert the PyTorch model into a usable CoreML model.
I don't think the problem you have is related to the tutorial itself.
Your problem is, I guess, how to use this model into an iOS application.

I'll update the tutorial soon to explain this part as well.
Please read my other GitHub project to find an answer to your question.
(See section "ONNX to CoremML conversion: Image version")

https://github.com/vincentfpgarcia/cookbook/blob/master/pytorch/pytorch-to-coreml.md
